#Docker secret- contains secret to push docker image
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0ZWNoaWV2ZWUiLCJwYXNzd29yZCI6InZpbm9kQDEyMyIsImVtYWlsIjoidGVjaGlldmVlIiwiYXV0aCI6ImRHVmphR2xsZG1WbE9uWnBibTlrUURFeU13PT0ifX19
kind: Secret
metadata:
  name: docker-secret
  namespace: servian
  selfLink: /api/v1/namespaces/default/secrets/docker-secret
type: kubernetes.io/dockerconfigjson
